// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrkaEval.Api.Data;

#nullable disable

namespace OrkaEval.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrkaEval.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CycleEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CycleStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<int?>("EvaluatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("UserId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.FormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<int?>("CycleId")
                        .HasColumnType("integer");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CoachId");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.Candidate", b =>
                {
                    b.HasOne("OrkaEval.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.Coach", b =>
                {
                    b.HasOne("OrkaEval.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.Evaluation", b =>
                {
                    b.HasOne("OrkaEval.Api.Models.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrkaEval.Api.Models.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrkaEval.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OrkaEval.Api.Models.CheckInSection", "CheckIn", b1 =>
                        {
                            b1.Property<int>("EvaluationId")
                                .HasColumnType("integer");

                            b1.Property<string>("BiggestWin")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<List<string>>("MoodEmojis")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int>("StressLevel")
                                .HasColumnType("integer");

                            b1.Property<string>("Wellbeing")
                                .HasColumnType("text");

                            b1.Property<string>("WhyFeeling")
                                .HasColumnType("text");

                            b1.HasKey("EvaluationId");

                            b1.ToTable("Evaluations");

                            b1.ToJson("CheckIn");

                            b1.WithOwner()
                                .HasForeignKey("EvaluationId");
                        });

                    b.OwnsOne("OrkaEval.Api.Models.CoachingSection", "Coaching", b1 =>
                        {
                            b1.Property<int>("EvaluationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Acknowledgement")
                                .HasColumnType("text");

                            b1.Property<string>("Alignment")
                                .HasColumnType("text");

                            b1.Property<string>("AnythingElse")
                                .HasColumnType("text");

                            b1.Property<string>("Autonomy")
                                .HasColumnType("text");

                            b1.Property<string>("Avoiding")
                                .HasColumnType("text");

                            b1.Property<int>("BandwidthLevel")
                                .HasColumnType("integer");

                            b1.Property<string>("Certifications")
                                .HasColumnType("text");

                            b1.Property<string>("Challenge")
                                .HasColumnType("text");

                            b1.Property<string>("Communication")
                                .HasColumnType("text");

                            b1.Property<string>("DesiredImpact")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<List<string>>("DevelopmentTopics")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("EasierSupport")
                                .HasColumnType("text");

                            b1.Property<string>("EmojiWhy")
                                .HasColumnType("text");

                            b1.Property<string>("Etiquette")
                                .HasColumnType("text");

                            b1.Property<string>("FeedbackReceived")
                                .HasColumnType("text");

                            b1.Property<string>("FiveYear")
                                .HasColumnType("text");

                            b1.Property<string>("GoalsFocused")
                                .HasColumnType("text");

                            b1.Property<string>("JoyThing")
                                .HasColumnType("text");

                            b1.Property<string>("Meaningful")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<List<string>>("MoodEmojis")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("MoveForward")
                                .HasColumnType("text");

                            b1.Property<string>("Navigating")
                                .HasColumnType("text");

                            b1.Property<string>("NextSteps")
                                .HasColumnType("text");

                            b1.Property<string>("NoValue")
                                .HasColumnType("text");

                            b1.Property<string>("ProfDevTopic")
                                .HasColumnType("text");

                            b1.Property<string>("ProfFeedback")
                                .HasColumnType("text");

                            b1.Property<string>("ProjGoals")
                                .HasColumnType("text");

                            b1.Property<string>("ProudOf")
                                .HasColumnType("text");

                            b1.Property<string>("PurposeNow")
                                .HasColumnType("text");

                            b1.Property<string>("RatingWhy")
                                .HasColumnType("text");

                            b1.Property<int?>("SessionRating")
                                .HasColumnType("integer");

                            b1.Property<string>("Stretch")
                                .HasColumnType("text");

                            b1.Property<string>("Takeaway")
                                .HasColumnType("text");

                            b1.Property<string>("TeamSupport")
                                .HasColumnType("text");

                            b1.Property<string>("Tried")
                                .HasColumnType("text");

                            b1.Property<string>("WeekWin")
                                .HasColumnType("text");

                            b1.Property<string>("WinPossible")
                                .HasColumnType("text");

                            b1.HasKey("EvaluationId");

                            b1.ToTable("Evaluations");

                            b1.ToJson("Coaching");

                            b1.WithOwner()
                                .HasForeignKey("EvaluationId");
                        });

                    b.OwnsOne("OrkaEval.Api.Models.CompetenciesSection", "Competencies", b1 =>
                        {
                            b1.Property<int>("EvaluationId")
                                .HasColumnType("integer");

                            b1.HasKey("EvaluationId");

                            b1.ToTable("Evaluations");

                            b1.ToJson("Competencies");

                            b1.WithOwner()
                                .HasForeignKey("EvaluationId");

                            b1.OwnsOne("OrkaEval.Api.Models.CompetencyRating", "Communication", b2 =>
                                {
                                    b2.Property<int>("CompetenciesSectionEvaluationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("EvaluatorNotes")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("EvaluatorRating")
                                        .HasColumnType("integer");

                                    b2.Property<string>("SelfAction")
                                        .HasColumnType("text");

                                    b2.Property<string>("SelfEvidence")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("SelfRating")
                                        .HasColumnType("integer");

                                    b2.HasKey("CompetenciesSectionEvaluationId");

                                    b2.ToTable("Evaluations");

                                    b2.WithOwner()
                                        .HasForeignKey("CompetenciesSectionEvaluationId");
                                });

                            b1.OwnsOne("OrkaEval.Api.Models.CompetencyRating", "Culture", b2 =>
                                {
                                    b2.Property<int>("CompetenciesSectionEvaluationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("EvaluatorNotes")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("EvaluatorRating")
                                        .HasColumnType("integer");

                                    b2.Property<string>("SelfAction")
                                        .HasColumnType("text");

                                    b2.Property<string>("SelfEvidence")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("SelfRating")
                                        .HasColumnType("integer");

                                    b2.HasKey("CompetenciesSectionEvaluationId");

                                    b2.ToTable("Evaluations");

                                    b2.WithOwner()
                                        .HasForeignKey("CompetenciesSectionEvaluationId");
                                });

                            b1.OwnsOne("OrkaEval.Api.Models.CompetencyRating", "GrowthLearning", b2 =>
                                {
                                    b2.Property<int>("CompetenciesSectionEvaluationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("EvaluatorNotes")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("EvaluatorRating")
                                        .HasColumnType("integer");

                                    b2.Property<string>("SelfAction")
                                        .HasColumnType("text");

                                    b2.Property<string>("SelfEvidence")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("SelfRating")
                                        .HasColumnType("integer");

                                    b2.HasKey("CompetenciesSectionEvaluationId");

                                    b2.ToTable("Evaluations");

                                    b2.WithOwner()
                                        .HasForeignKey("CompetenciesSectionEvaluationId");
                                });

                            b1.OwnsOne("OrkaEval.Api.Models.CompetencyRating", "Leadership", b2 =>
                                {
                                    b2.Property<int>("CompetenciesSectionEvaluationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("EvaluatorNotes")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("EvaluatorRating")
                                        .HasColumnType("integer");

                                    b2.Property<string>("SelfAction")
                                        .HasColumnType("text");

                                    b2.Property<string>("SelfEvidence")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("SelfRating")
                                        .HasColumnType("integer");

                                    b2.HasKey("CompetenciesSectionEvaluationId");

                                    b2.ToTable("Evaluations");

                                    b2.WithOwner()
                                        .HasForeignKey("CompetenciesSectionEvaluationId");
                                });

                            b1.OwnsOne("OrkaEval.Api.Models.CompetencyRating", "TechnicalSkills", b2 =>
                                {
                                    b2.Property<int>("CompetenciesSectionEvaluationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("EvaluatorNotes")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("EvaluatorRating")
                                        .HasColumnType("integer");

                                    b2.Property<string>("SelfAction")
                                        .HasColumnType("text");

                                    b2.Property<string>("SelfEvidence")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<int?>("SelfRating")
                                        .HasColumnType("integer");

                                    b2.HasKey("CompetenciesSectionEvaluationId");

                                    b2.ToTable("Evaluations");

                                    b2.WithOwner()
                                        .HasForeignKey("CompetenciesSectionEvaluationId");
                                });

                            b1.Navigation("Communication")
                                .IsRequired();

                            b1.Navigation("Culture")
                                .IsRequired();

                            b1.Navigation("GrowthLearning")
                                .IsRequired();

                            b1.Navigation("Leadership")
                                .IsRequired();

                            b1.Navigation("TechnicalSkills")
                                .IsRequired();
                        });

                    b.OwnsOne("OrkaEval.Api.Models.OpenDiscussionSection", "OpenDiscussion", b1 =>
                        {
                            b1.Property<int>("EvaluationId")
                                .HasColumnType("integer");

                            b1.Property<string>("IceBreaker")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<string>("ReviewPeriod")
                                .HasColumnType("text");

                            b1.Property<string>("RoleTrack")
                                .HasColumnType("text");

                            b1.Property<string>("SessionStatus")
                                .HasColumnType("text");

                            b1.Property<string>("Takeaway")
                                .HasColumnType("text");

                            b1.Property<string>("TopOfMind")
                                .HasColumnType("text");

                            b1.HasKey("EvaluationId");

                            b1.ToTable("Evaluations");

                            b1.ToJson("OpenDiscussion");

                            b1.WithOwner()
                                .HasForeignKey("EvaluationId");
                        });

                    b.OwnsOne("OrkaEval.Api.Models.ReflectionSection", "Reflection", b1 =>
                        {
                            b1.Property<int>("EvaluationId")
                                .HasColumnType("integer");

                            b1.Property<string>("BiggestChallenge")
                                .HasColumnType("text");

                            b1.Property<string>("Comments")
                                .HasColumnType("text");

                            b1.Property<string>("DoDifferently")
                                .HasColumnType("text");

                            b1.Property<string>("Goal1")
                                .HasColumnType("text");

                            b1.Property<string>("Goal2")
                                .HasColumnType("text");

                            b1.Property<string>("Goal3")
                                .HasColumnType("text");

                            b1.Property<string>("GreatestAchievement")
                                .HasColumnType("text");

                            b1.Property<string>("PriorityCompetency")
                                .HasColumnType("text");

                            b1.Property<string>("SupervisorSupport")
                                .HasColumnType("text");

                            b1.HasKey("EvaluationId");

                            b1.ToTable("Evaluations");

                            b1.ToJson("Reflection");

                            b1.WithOwner()
                                .HasForeignKey("EvaluationId");
                        });

                    b.OwnsOne("OrkaEval.Api.Models.SessionSection", "Session", b1 =>
                        {
                            b1.Property<int>("EvaluationId")
                                .HasColumnType("integer");

                            b1.Property<string>("ActionPlanDates")
                                .HasColumnType("text");

                            b1.Property<string>("ActionPlanGoal1")
                                .HasColumnType("text");

                            b1.Property<string>("ActionPlanGoal2")
                                .HasColumnType("text");

                            b1.Property<string>("ActionPlanGoal3")
                                .HasColumnType("text");

                            b1.Property<string>("AgreedGoals")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("IcebreakerEvaluator")
                                .HasColumnType("text");

                            b1.Property<string>("IcebreakerTeamMember")
                                .HasColumnType("text");

                            b1.Property<string>("KeyTakeaways")
                                .HasColumnType("text");

                            b1.Property<string>("NextSteps")
                                .HasColumnType("text");

                            b1.Property<string>("SessionFormat")
                                .HasColumnType("text");

                            b1.Property<int?>("SessionRating")
                                .HasColumnType("integer");

                            b1.HasKey("EvaluationId");

                            b1.ToTable("Evaluations");

                            b1.ToJson("Session");

                            b1.WithOwner()
                                .HasForeignKey("EvaluationId");
                        });

                    b.Navigation("CheckIn")
                        .IsRequired();

                    b.Navigation("Coaching")
                        .IsRequired();

                    b.Navigation("Competencies")
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Evaluator");

                    b.Navigation("OpenDiscussion")
                        .IsRequired();

                    b.Navigation("Reflection")
                        .IsRequired();

                    b.Navigation("Session")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrkaEval.Api.Models.FormSubmission", b =>
                {
                    b.HasOne("OrkaEval.Api.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrkaEval.Api.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Coach");
                });
#pragma warning restore 612, 618
        }
    }
}
